# Site settings
title: Bra1n
description: Hack. Evolve. Improve.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ickogz.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bra1n.net
user_description: La seguridad de la información es un campo que requiere una alta especialización y una constante actualizacion. <br>Nosotros entrenamos todos los días para brindar las mejores soluciones a nuestros clientes. 
user_title: Especialistas en ciberseguridad
email: bernardo.viqueira@bra1n.net
twitter_username: Bra1nNet
github_username:  ickogz
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
